# Habilitar descubrimiento clásico de cluster
cluster_formation.peer_discovery_backend = rabbit_peer_discovery_classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-2

# Tiempo de espera para limpieza de nodos (ms)
cluster_formation.node_cleanup.interval = 10000

# Ubicación predeterminada de colas
queue_master_location = all