spring.application.name=eureka-server

# ms-eureka/application.properties
server.port=8761

#eureka.instance.hostname=localhost
eureka.instance.hostname=eureka-server

# El servidor NO se registra en si mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Tiempo para marcar un servicio como DOWN
eureka.server.eviction-interval-timer-in-ms=10000

spring.cloud.compatibility-verifier.enabled=false